server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://wcjeong0404@bitbucket.org/wcjeong0404/cloud-config.git
          username: wcjeong0404
          password: hist2020
